# mem5_game/Makefile.toml
# Workspace with members

[config]
skip_core_tasks = true

#region: public callable tasks/flows
[tasks.default]
description = "show list of callable public tasks"
clear = true
command = "cargo"
args = ["make","--list-all-steps"]

[tasks.dev]
description = "cargo make dev for every workspace member"
workspace = true
command = "cargo"
args = ["make","dev"]

[tasks.release]
description = "cargo make release for every workspace member"
workspace = true
clear=true
command = "cargo"
args = ["make","release"]

[tasks.doc]
description = "cargo make doc for every workspace member"
workspace = true
clear=true
command = "cargo"
args = ["make","doc"]

[tasks.publish]
description = "TODO: copy the content of /mem5_game/webfolder/mem5/ to google vm. How?? ssh ?"
workspace = true
clear=true
command="cargo"
args=["make", "publish"]

#endregion
