# mem5_game/Makefile.toml
# Workspace with members

[config]
skip_core_tasks = true

#region: public callable tasks/flows
[tasks.default]
description = "show list of callable public tasks"
workspace = false
clear = true
command = "cargo"
args = ["make","--list-all-steps"]

[tasks.dev]
description = "cargo make dev for every workspace member"
workspace = true
command = "cargo"
args = ["make","dev"]

[tasks.release]
description = "cargo make release for every workspace member"
workspace = true
clear=true
command = "cargo"
args = ["make","release"]

[tasks.doc]
description = "cargo make doc for every workspace member"
workspace = true
clear=true
command = "cargo"
args = ["make","doc"]


[tasks.sshadd]
description = "remember my ssh passphrase"
workspace = false
clear = true
script = [
    "ssh-add /home/luciano/.ssh/luciano_googlecloud",
    "ssh-add /home/luciano/.ssh/lucianobestia_mac",
    "ssh-add -l",
]

[tasks.gitpush]
description = "Push to github. Uses the sshagesnt."
workspace = false
clear = true
script = [
    "git push",
]

[tasks.publish]
description = "Copy the content of /mem5_game/webfolder to //googlecloud/ folder and then to google vm with use of sshagent."
workspace = false
clear = true
# backslash is the escape character for all other special characters.
# and then another time I have to escape the backslash. So 4 backslash for one backslash.
script = [
    "rsync -avz --delete-after /home/luciano/rustprojects/mem5_game/webfolder/ /home/luciano/rustprojects/googlecloud/var/www/webapps/mem5_game/",
    "ssh -tt -i /home/luciano/.ssh/luciano_googlecloud luciano_bestia@34.87.17.103 screen -dr mem5-8085 -X stuff $'\\\\003'",
    "ssh -tt -i /home/luciano/.ssh/luciano_googlecloud luciano_bestia@34.87.17.103 screen -dr mem5-8085 -X stuff 'cd\\ \\/var\\/www\\/webapps\\/mem5_game\\\\n'",
    "rsync -e ssh -avz --delete-after /home/luciano/rustprojects/googlecloud/var/www/webapps/mem5_game/ luciano_bestia@34.87.17.103:/var/www/webapps/mem5_game/",
    "ssh -tt -i /home/luciano/.ssh/luciano_googlecloud luciano_bestia@34.87.17.103 screen -dr mem5-8085 -X stuff 'chmod\\ \\+x\\ mem5_server\\\\n'",
    "ssh -tt -i /home/luciano/.ssh/luciano_googlecloud luciano_bestia@34.87.17.103 screen -dr mem5-8085 -X stuff 'sudo\\ \\.\\/mem5_server\\\\n'",
]

#endregion
