# mem5_game/mem5_common/Makefile.toml
#https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: public callable tasks/flows

    [tasks.default]
    description = "show list of public callable tasks"
    clear = true
    command = "cargo"
    args = ["make","--list-all-steps"]

    [tasks.dev]
    description = "cargo build development"
    clear=true
    dependencies = [
        "lmake_version_from_date",
        "build-dev"]

    [tasks.release]
    description = "cargo build release"
    clear=true
    dependencies = [
       # "lmake_version_from_date",
        "build-release"]

    [tasks.doc]
    description = "call cargo doc"
    clear=true
    dependencies = [
        "insert-readme",
        "cargo-doc",
        "cargo-docs-copy"
    ]
#endregion


[tasks.build-dev]
clear=true
private=true
command = "cargo"
args = ["build"]

[tasks.build-release]
clear=true
private=true
command = "cargo"
args = ["build","--release"]

[tasks.insert-readme]
clear = true
private = true
description = "copy the content of readme.md into *.rs comments (for the docs)"
script= ["..\\..\\utils\\lmake_readme.exe"]

[tasks.cargo-doc]
clear = true
private = true
description = "call cargo doc"
command="cargo"
args=["doc","--no-deps","--document-private-items","--open"]

[tasks.cargo-docs-copy]
clear = true
private = true
script = [
    "xcopy c:\\Users\\Luciano\\rustprojects\\mem5_game\\target\\doc\\*.* c:\\Users\\Luciano\\rustprojects\\mem5_game\\docs\\ /e /i /y /s ",
]

[tasks.lmake_version_from_date]
clear = true
private = true
description = "in cargo.toml change version to today date"
script= ["..\\..\\utils\\lmake_version_from_date.exe"]

